### ISSUE TITLE
Create Course via URL

### ISSUE THREAD

**Issue by cameron5906** [cameron5906/eduvize-ai#29]
## Overview
Allow users to provide a URL to a resource the web in order to scan it and create a course syllabus on its contents.

Some examples are:
- **A job listing**: Read through the requirements for a provided role and determine what knowledge the user should have in order to apply and make it through an interview process
- **Documentation**: Read through documentation for an API and derive enough context to create a course on how to use it effectively
- **A GitHub repository**: Read through documentation and potentially embed the source code of a Github repository to understand it enough to create a course on how to use the project

## Objectives
The main objective of this issue is not to implement this functionality end-to-end, but rather develop the backend framework for creating the data that will be fed into the course outline generation prompt.

### Browsing Online Resources
Utilize Selenium and Chrome Driver to provide an interface to the web that can be controlled by GPT-4o. This process should expose several tools to enable the model to scroll the page, click on links by title, and provide screen rendering for visual processing.

### Information Gathering Prompt
Create a new prompt that can leverage the browsing component in order to visit a provided URL and extract information.

**Comment by mattcohen28** [comment]
Additional example:

- **Certification requirements/description**: leverage certification details and requirements to ensure the necessary material gets included in the generate course

**Comment by cameron5906** [comment]
Moved to Trello
